// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex                  string   `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_ba624daa7271c2b4, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

type PersonRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonRequest) Reset()         { *m = PersonRequest{} }
func (m *PersonRequest) String() string { return proto.CompactTextString(m) }
func (*PersonRequest) ProtoMessage()    {}
func (*PersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_ba624daa7271c2b4, []int{1}
}
func (m *PersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonRequest.Unmarshal(m, b)
}
func (m *PersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonRequest.Marshal(b, m, deterministic)
}
func (dst *PersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonRequest.Merge(dst, src)
}
func (m *PersonRequest) XXX_Size() int {
	return xxx_messageInfo_PersonRequest.Size(m)
}
func (m *PersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PersonRequest proto.InternalMessageInfo

func (m *PersonRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PersonResponse struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonResponse) Reset()         { *m = PersonResponse{} }
func (m *PersonResponse) String() string { return proto.CompactTextString(m) }
func (*PersonResponse) ProtoMessage()    {}
func (*PersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_ba624daa7271c2b4, []int{2}
}
func (m *PersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonResponse.Unmarshal(m, b)
}
func (m *PersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonResponse.Marshal(b, m, deterministic)
}
func (dst *PersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonResponse.Merge(dst, src)
}
func (m *PersonResponse) XXX_Size() int {
	return xxx_messageInfo_PersonResponse.Size(m)
}
func (m *PersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PersonResponse proto.InternalMessageInfo

func (m *PersonResponse) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type ListPersonResponse struct {
	Person               []*Person `protobuf:"bytes,1,rep,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListPersonResponse) Reset()         { *m = ListPersonResponse{} }
func (m *ListPersonResponse) String() string { return proto.CompactTextString(m) }
func (*ListPersonResponse) ProtoMessage()    {}
func (*ListPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_ba624daa7271c2b4, []int{3}
}
func (m *ListPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPersonResponse.Unmarshal(m, b)
}
func (m *ListPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPersonResponse.Marshal(b, m, deterministic)
}
func (dst *ListPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPersonResponse.Merge(dst, src)
}
func (m *ListPersonResponse) XXX_Size() int {
	return xxx_messageInfo_ListPersonResponse.Size(m)
}
func (m *ListPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPersonResponse proto.InternalMessageInfo

func (m *ListPersonResponse) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "test.v1.Person")
	proto.RegisterType((*PersonRequest)(nil), "test.v1.PersonRequest")
	proto.RegisterType((*PersonResponse)(nil), "test.v1.PersonResponse")
	proto.RegisterType((*ListPersonResponse)(nil), "test.v1.ListPersonResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonServiceClient is the client API for PersonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonServiceClient interface {
	GetPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*PersonResponse, error)
	ListPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*ListPersonResponse, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) GetPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*PersonResponse, error) {
	out := new(PersonResponse)
	err := c.cc.Invoke(ctx, "/test.v1.PersonService/getPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceClient) ListPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*ListPersonResponse, error) {
	out := new(ListPersonResponse)
	err := c.cc.Invoke(ctx, "/test.v1.PersonService/listPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServiceServer is the server API for PersonService service.
type PersonServiceServer interface {
	GetPerson(context.Context, *PersonRequest) (*PersonResponse, error)
	ListPerson(context.Context, *PersonRequest) (*ListPersonResponse, error)
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.v1.PersonService/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).GetPerson(ctx, req.(*PersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonService_ListPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).ListPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.v1.PersonService/ListPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).ListPerson(ctx, req.(*PersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.v1.PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPerson",
			Handler:    _PersonService_GetPerson_Handler,
		},
		{
			MethodName: "listPerson",
			Handler:    _PersonService_ListPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_person_ba624daa7271c2b4) }

var fileDescriptor_person_ba624daa7271c2b4 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b,
	0x33, 0x54, 0xd2, 0xe3, 0x62, 0x0b, 0x00, 0x4b, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0xc5, 0xa9, 0x15,
	0x12, 0x4c, 0x60, 0x21, 0x10, 0x53, 0x49, 0x9e, 0x8b, 0x17, 0xa2, 0x3e, 0x28, 0xb5, 0xb0, 0x34,
	0xb5, 0xb8, 0x44, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x05, 0xaa, 0x89, 0x29, 0x33, 0x45, 0xc9, 0x92,
	0x8b, 0x0f, 0xa6, 0xa0, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x9d, 0x8b, 0x0d, 0x62, 0x37,
	0x58, 0x15, 0xb7, 0x11, 0xbf, 0x1e, 0xd4, 0x72, 0x3d, 0xa8, 0x42, 0xa8, 0xb4, 0x92, 0x2d, 0x97,
	0x90, 0x4f, 0x66, 0x71, 0x09, 0x1e, 0xed, 0xcc, 0x78, 0xb4, 0x1b, 0x4d, 0x60, 0x84, 0xb9, 0x2d,
	0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x86, 0x8b, 0x33, 0x3d, 0x15, 0x6a, 0x9e, 0x90,
	0x18, 0xba, 0x3e, 0x88, 0x07, 0xa4, 0xc4, 0x31, 0xc4, 0xa1, 0x16, 0x3b, 0x72, 0x71, 0xe5, 0xc0,
	0x9d, 0x83, 0x53, 0xbb, 0x34, 0x5c, 0x1c, 0xd3, 0xed, 0x49, 0x6c, 0xe0, 0xd0, 0x36, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xfd, 0x51, 0x57, 0xea, 0x7d, 0x01, 0x00, 0x00,
}
